name: Test

on: [test]

jobs:
  leak:
    name: Hello World
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: |
          echo $VALUE | base64
        env:
          VALUE: ${{ secrets.meow }}
